name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: web-app
    steps:
      - uses: actions/checkout@v2
